- hosts: all
  vars:
    zsh_antigen_bundles_extras:
      - nvm
      - joel-porquet/zsh-dircolors-solarized
    zsh_autosuggestions_bind_key: "^U"
    homebrew_user: vagrant
  tasks:
  - name: apt update and upgrade
    become: true
    apt:
      upgrade: yes
      update_cache: yes
      cache_valid_time: 86400
  roles:
    - viasite-ansible.zsh        
    - role: stephdewit.nvm
      become: true
      become_user: vagrant
      environment:
        NVM_DIR: /home/vagrant/.nvm
      nvm_version: latest
    - role: gantsign.sdkman
      sdkman_users:
        - vagrant
    - role: monolithprojects.homebrew
      become: true


