- hosts: all
  tasks:
  - name: Update apt cache
    become: yes
    apt: update_cache=yes
  - name: Install packages
    become: yes
    apt:
      pkg:
        - git
        - zsh
        - unzip
        - zip
      state: latest
  - name: create empty dot_zshrc
    file:
      path: /home/vagrant/.zshrc
      state: touch
      owner: vagrant
      group: vagrant
  - name: Make zsh default shell
    user:
      name: vagrant
      shell: /usr/bin/zsh
  - name: some task 
    shell: whoami

#   - debug:
#       var: whoami
