- hosts: all
  vars:
    zsh_antigen_bundles_extras:
      - nvm
      - joel-porquet/zsh-dircolors-solarized
    zsh_autosuggestions_bind_key: "^U"
  roles:
    - viasite-ansible.zsh        
    - role: stephdewit.nvm
      become: true
      become_user: vagrant
      environment:
        NVM_DIR: /home/vagrant/.nvm
      nvm_version: latest
      nvm_node_version: lts
    - role: gantsign.sdkman
      sdkman_users:
        - vagrant

