- hosts: all
  vars:
    homebrew_user: vagrant
    zsh_antigen_bundles_extras:
      - git
      - sudo
      - nvm
      - brew
      - zsh-users/zsh-autosuggestions
      - zsh-users/zsh-syntax-highlighting
    zsh_autosuggestions_bind_key: "^U"
  tasks:
  - name: 'apt update'
    become: true
    apt:
      update_cache: yes

  - name: 'apt install python3'
    become: true
    apt:
      name: python3
      state: present

  - name: "apt install python3-pip"
    become: true
    apt:
      name: python3-pip
      state: present
      update_cache: yes

  - name: "apt install zip"
    become: true
    apt:
      name: zip
      state: present
      update_cache: yes

  - name: "apt install unzip"
    become: true
    apt:
      name: unzip
      state: present
      update_cache: yes

  roles:
    - role: monolithprojects.homebrew
      become: true
    - role: viasite-ansible.zsh
    - role: gikeymarcia.neovim
      become: true
    - role: stephdewit.nvm
      become: true
      become_user: vagrant
      environment:
        NVM_DIR: /home/vagrant/.nvm
      nvm_version: latest
      nvm_node_version: lts
    - role: gantsign.sdkman
      become: true
      sdkman_users:
        - vagrant
