- hosts: all
  vars:
    homebrew_user: vagrant
    zsh_antigen_bundles_extras:
      - git
      - sudo
      - zsh-users/zsh-autosuggestions
      - zsh-users/zsh-syntax-highlighting
    zsh_autosuggestions_bind_key: "^U"
  tasks:
  - name: apt update and upgrade
    become: true
    apt:
      upgrade: yes
      update_cache: yes
      cache_valid_time: 86400
  roles:
    - role: stephdewit.nvm
      become: true
      become_user: vagrant
      environment:
        NVM_DIR: /home/vagrant/.nvm
      nvm_version: latest
    - role: gantsign.sdkman
      sdkman_users:
        - vagrant
    - role: monolithprojects.homebrew
      become: true
    - role: viasite-ansible.zsh